# Generated by Django 3.1.4 on 2020-12-24 13:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Place of Birth')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=2, verbose_name='Gender')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('religion', models.CharField(choices=[('BU', 'Buddha'), ('KP', 'Kristen Protestan'), ('KK', 'Kristen Katolik'), ('HI', 'Hindu'), ('IS', 'Islam')], max_length=2, verbose_name='Religion')),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5, verbose_name='Postal Code')),
                ('province', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('line_id', models.CharField(max_length=50, verbose_name='LINE ID')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('whatsapp_no', models.CharField(max_length=15, verbose_name='Whatsapp Number')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Number')),
                ('concentration', models.CharField(max_length=10)),
                ('school_location', models.CharField(max_length=50, verbose_name='School Location')),
                ('graduation_year', models.SmallIntegerField(verbose_name='Graduation Year')),
                ('father_name', models.CharField(max_length=50, verbose_name="Father's Full Name")),
                ('father_mobile_number', models.CharField(max_length=15, verbose_name="Father's Phone Number")),
                ('father_mortality_status', models.CharField(choices=[('AL', 'Alive'), ('DT', 'Deceased')], default='AL', max_length=2, verbose_name='Mortality Status')),
                ('father_address', models.TextField(verbose_name="Father's Address")),
                ('mother_name', models.CharField(max_length=50, verbose_name="Mother's Full Name")),
                ('mother_mobile_number', models.CharField(max_length=15, verbose_name="Mother's Phone Number")),
                ('mother_mortality_status', models.CharField(choices=[('AL', 'Alive'), ('DT', 'Deceased')], default='AL', max_length=2, verbose_name='Mortality Status')),
                ('mother_address', models.TextField(verbose_name="Mother's Address")),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Guardian's Full Name")),
                ('guardian_mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name="Guardian's Phone Number")),
                ('guardian_mortality_status', models.CharField(blank=True, choices=[('AL', 'Alive'), ('DT', 'Deceased')], default='AL', max_length=2, null=True, verbose_name='Mortality Status')),
                ('guardian_address', models.TextField(blank=True, null=True, verbose_name="Guardian's Address")),
                ('study_program', models.CharField(choices=[('ACC', 'Accounting'), ('ENT', 'Entrepreneurship'), ('HOS', 'Hospitality Management'), ('INT', 'International Trade'), ('INF', 'Information System'), ('MGM', 'Management')], max_length=3, verbose_name='Study Program')),
                ('schedule', models.CharField(choices=[('NO', 'Afternoon (05.00 PM)'), ('NI', 'Evening (07.00 PM)')], max_length=2, verbose_name='Class Schedule')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
