# Generated by Django 3.1.4 on 2021-01-12 05:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('BA', 'Business'), ('TI', 'Technology'), ('HM', 'Hotel Management')], max_length=2)),
                ('image', models.ImageField(default='default.jpg', upload_to='major_pics')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Place of Birth')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2, verbose_name='Gender')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('religion', models.CharField(choices=[('BU', 'Buddha'), ('KP', 'Kristen Protestan'), ('KK', 'Kristen Katolik'), ('HI', 'Hindu'), ('IS', 'Islam'), ('OT', 'Other')], max_length=2, verbose_name='Religion')),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5, verbose_name='Postal Code')),
                ('province', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('line_id', models.CharField(max_length=50, verbose_name='LINE ID')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('whatsapp_no', models.CharField(max_length=15, verbose_name='Whatsapp Number')),
                ('school_name', models.CharField(max_length=100, verbose_name='Former School Name')),
                ('concentration', models.CharField(max_length=10)),
                ('school_location', models.CharField(max_length=50, verbose_name='School Location')),
                ('graduation_year', models.SmallIntegerField(verbose_name='Graduation Year')),
                ('father_name', models.CharField(max_length=50, verbose_name="Father's Full Name")),
                ('father_mobile_number', models.CharField(max_length=15, verbose_name="Father's Phone Number")),
                ('father_mortality_status', models.CharField(choices=[('AL', 'Alive'), ('DT', 'Deceased')], max_length=2, verbose_name='Mortality Status')),
                ('father_address', models.TextField(verbose_name="Father's Address")),
                ('mother_name', models.CharField(max_length=50, verbose_name="Mother's Full Name")),
                ('mother_mobile_number', models.CharField(max_length=15, verbose_name="Mother's Phone Number")),
                ('mother_mortality_status', models.CharField(choices=[('AL', 'Alive'), ('DT', 'Deceased')], max_length=2, verbose_name='Mortality Status')),
                ('mother_address', models.TextField(verbose_name="Mother's Address")),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Guardian's Full Name")),
                ('guardian_mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name="Guardian's Phone Number")),
                ('guardian_mortality_status', models.CharField(blank=True, choices=[('AL', 'Alive'), ('DT', 'Deceased')], max_length=2, null=True, verbose_name='Mortality Status')),
                ('guardian_address', models.TextField(blank=True, null=True, verbose_name="Guardian's Address")),
                ('schedule', models.CharField(choices=[('NO', 'Afternoon (05.00 PM)'), ('NI', 'Evening (07.00 PM)')], max_length=2, verbose_name='Class Schedule')),
                ('graduation_program', models.CharField(blank=True, choices=[('NDP', 'National Degree Program'), ('JDP', 'Joint Degree Program')], max_length=3, null=True, verbose_name='Graduation Program')),
                ('registration_paid', models.BooleanField(default=False, verbose_name='Registration Paid')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regform.studyprogram', verbose_name='Study Program')),
            ],
            options={
                'verbose_name': 'Student List',
            },
        ),
    ]
