# Generated by Django 3.1.4 on 2020-12-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0002_auto_20201224_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='religion',
            field=models.CharField(choices=[('BU', 'Buddha'), ('KP', 'Kristen Protestan'), ('KK', 'Kristen Katolik'), ('HI', 'Hindu'), ('IS', 'Islam'), ('OT', 'Other')], max_length=2, verbose_name='Religion'),
        ),
    ]
