# Generated by Django 3.1.4 on 2020-12-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0003_auto_20201226_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='father_mortality_status',
            field=models.CharField(choices=[('AL', 'Alive'), ('DT', 'Deceased')], max_length=2, verbose_name='Mortality Status'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='guardian_mortality_status',
            field=models.CharField(blank=True, choices=[('AL', 'Alive'), ('DT', 'Deceased')], max_length=2, null=True, verbose_name='Mortality Status'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mother_mortality_status',
            field=models.CharField(choices=[('AL', 'Alive'), ('DT', 'Deceased')], max_length=2, verbose_name='Mortality Status'),
        ),
    ]
