# Generated by Django 3.1.4 on 2020-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0004_auto_20201226_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'Student List'},
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='school_name',
            field=models.CharField(max_length=100, verbose_name='Former School Name'),
        ),
    ]
