# Generated by Django 3.1.4 on 2020-12-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0005_auto_20201226_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='graduation_program',
            field=models.CharField(blank=True, choices=[('NDP', 'National Degree Program'), ('JDP', 'Joint Degree Program')], max_length=3, null=True, verbose_name='Graduation Program'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='registration_paid',
            field=models.BooleanField(default=False),
        ),
    ]
